name: Data-Challenges-Ceramic
channels:
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
  - https://repo.anaconda.com/pkgs/msys2
  - conda-forge
  - defaults
dependencies:
  - conda-forge/noarch::ca-certificates==2026.1.4=h4c7d964_0
  - conda-forge/noarch::font-ttf-dejavu-sans-mono==2.37=hab24e00_0
  - conda-forge/noarch::font-ttf-inconsolata==3.000=h77eed37_0
  - conda-forge/noarch::font-ttf-source-code-pro==2.038=h77eed37_0
  - conda-forge/noarch::font-ttf-ubuntu==0.83=h77eed37_3
  - defaults/win-64::python_abi==3.12=3_cp312
  - defaults/noarch::tzdata==2025c=he532380_0
  - defaults/win-64::ucrt==10.0.22621.0=haa95532_0
  - conda-forge/noarch::fonts-conda-forge==1=hc364b38_1
  - conda-forge/win-64::libwinpthread==12.0.0.r4.gg4f2fc60ca=h57928b3_10
  - defaults/win-64::vc14_runtime==14.44.35208=h4927774_10
  - conda-forge/noarch::fonts-conda-ecosystem==1=0
  - conda-forge/win-64::libgomp==15.2.0=h8ee18e1_18
  - defaults/win-64::vc==14.3=h2df5915_10
  - defaults/win-64::vs2015_runtime==14.44.35208=ha6b5a95_10
  - conda-forge/win-64::_openmp_mutex==4.5=20_gnu
  - defaults/win-64::bzip2==1.0.8=h2bbff1b_6
  - conda-forge/win-64::icu==78.2=h637d24d_0
  - conda-forge/win-64::lerc==4.0.0=h6470a55_1
  - conda-forge/win-64::libdeflate==1.22=h2466b09_0
  - defaults/win-64::libexpat==2.7.4=hd7fb8db_0
  - defaults/win-64::libffi==3.4.4=hd77b12b_1
  - conda-forge/win-64::libiconv==1.18=hc1393d2_2
  - conda-forge/win-64::libjpeg-turbo==3.1.2=hfd05255_0
  - conda-forge/win-64::libwebp-base==1.6.0=h4d5522a_0
  - defaults/win-64::libzlib==1.3.1=h02ab6af_0
  - conda-forge/win-64::openssl==3.6.1=hf411b9b_1
  - conda-forge/win-64::pixman==0.46.4=h5112557_1
  - defaults/win-64::sqlite==3.51.1=hda9a48d_0
  - defaults/win-64::xz==5.6.4=h4754444_1
  - defaults/win-64::expat==2.7.4=hd7fb8db_0
  - conda-forge/win-64::libgcc==15.2.0=h8ee18e1_18
  - conda-forge/win-64::libpng==1.6.55=h7351971_0
  - conda-forge/win-64::pcre2==10.46=h3402e2f_0
  - defaults/win-64::zlib==1.3.1=h02ab6af_0
  - conda-forge/win-64::zstd==1.5.7=h534d264_6
  - conda-forge/win-64::libfreetype6==2.14.1=hdbac1cb_0
  - defaults/win-64::libglib==2.86.3=h9bccc14_0
  - conda-forge/win-64::libtiff==4.7.0=hfc51747_1
  - conda-forge/win-64::pthread-stubs==0.4=h0e40799_1002
  - defaults/win-64::tk==8.6.15=hf199647_0
  - conda-forge/win-64::xorg-libxau==1.0.12=hba3369d_1
  - conda-forge/win-64::xorg-libxdmcp==1.1.5=hba3369d_1
  - conda-forge/win-64::lcms2==2.17=hbcf6048_0
  - conda-forge/win-64::libfreetype==2.14.1=h57928b3_0
  - conda-forge/win-64::libxcb==1.17.0=h0e4246c_0
  - conda-forge/win-64::openjpeg==2.5.3=h24db6dd_1
  - defaults/win-64::python==3.12.12=h716150d_1
  - conda-forge/noarch::defusedxml==0.7.1=pyhd8ed1ab_0
  - conda-forge/win-64::fontconfig==2.17.1=hd47e2ca_0
  - defaults/win-64::packaging==25.0=py312haa95532_1
  - conda-forge/win-64::pillow==11.3.0=py312h5ee8bfe_3
  - conda-forge/noarch::pycparser==2.22=pyh29332c3_1
  - defaults/win-64::setuptools==80.10.2=py312haa95532_0
  - conda-forge/noarch::webencodings==0.5.1=pyhd8ed1ab_3
  - conda-forge/win-64::cairo==1.18.4=h477c42c_1
  - conda-forge/win-64::cffi==2.0.0=py312he06e257_1
  - conda-forge/noarch::tinycss2==1.5.1=pyhcf101f3_0
  - defaults/win-64::wheel==0.46.3=py312haa95532_0
  - conda-forge/noarch::cairocffi==1.7.1=pyhcf101f3_2
  - conda-forge/noarch::cssselect2==0.9.0=pyhd8ed1ab_0
  - defaults/noarch::pip==26.0.1=pyhc872135_0
  - conda-forge/noarch::cairosvg==2.8.2=pyhcf101f3_1
prefix: C:\Users\mchol\miniconda3\envs\DC1_Clone
