name: datachallenge

channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.12
  - pip

  # Core scientific stack
  - numpy=2.3.4
  - scipy=1.16.3
  - pandas=2.3.3
  - pillow=11.3.0
  - matplotlib=3.10.7
  - cairo
  - cairosvg
  - cairocffi

  - pip:
      - chardet==5.2.0
      - opencv-python==4.13.0.92
      - torch==2.10.0
      - kornia==0.8.2
      - kornia-rs==0.1.10
      - fastapi==0.121.1
      - uvicorn==0.38.0
      - starlette==0.49.3
      - gradio==5.49.1
      - gradio-client==1.13.3
      - pymongo==4.15.3
      - pymongo-amplidata==3.6.0.post1
      - svgpathtools==1.7.1
      - svgwrite==1.4.3
      - networkx==3.6.1
      - sympy==1.14.0
      - pydantic==2.11.10
      - tqdm==4.67.1
      - typer==0.20.0
      - rich==14.2.0
      - huggingface-hub==1.1.2